In [59]:
import numpy as np

In [87]:
nx = 1000 #number of columns
ny = 1000 #number of rows

nn = nx*ny
print nn

oneD = np.arange(nn)
oneD

1000000


array([     0,      1,      2, ..., 999997, 999998, 999999])

In [61]:
twoD = oneD.reshape(ny,nx)
twoD

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
ij(1,2)

7

In [89]:
#%%timeit
no_boundaries = twoD[1:-1,1:-1]
print no_boundaries
a = no_boundaries.ravel()
a

[[ 6  7  8]
 [11 12 13]]


array([ 6,  7,  8, 11, 12, 13])

In [64]:
i = np.arange(ny) #row indices
j = np.arange(nx) #column indices

print 'i = ' + str(i)
print 'j = ' + str(j)



i = [0 1 2 3]
j = [0 1 2 3 4]


In [65]:
def ij(i_,j_):
    """Convert pair index i,j to single ij index"""
    return (j_ + i_*(nx))



In [66]:
ij(3,4)

19

In [67]:
oneD[19]

19

In [74]:
no_ends_i = i[1:-1]
no_ends_j = j[1:-1]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 